In [1]:
import pandas as pd
import os
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

num_layers = [6, 5, 4, 3]
num_neurons = [500, 400, 300, 200, 100, 10]

In [2]:
df_relu = pd.read_pickle(os.path.join('orig_measurement_df','exe_time_measurement_relu_arch.pkl'))
df_tanh = pd.read_pickle(os.path.join('orig_measurement_df','exe_time_measurement_tanh_arch.pkl'))
df_sigmoid = pd.read_pickle(os.path.join('orig_measurement_df','exe_time_measurement_sigmoid_arch.pkl'))

In [3]:
mean_relu = []
mean_tanh = []
mean_sigmoid = []

for i in num_layers:
    mean_relu.append([])
    mean_tanh.append([])
    mean_sigmoid.append([])
    for j in num_neurons:
        mean_relu[-1].append(df_relu.loc[(df_relu['num_layers'] == i) & (df_relu['num_neurons'] == j)]['measurement'].mean())
        mean_tanh[-1].append(df_tanh.loc[(df_tanh['num_layers'] == i) & (df_tanh['num_neurons'] == j)]['measurement'].mean())
        mean_sigmoid[-1].append(df_sigmoid.loc[(df_sigmoid['num_layers'] == i) & (df_sigmoid['num_neurons'] == j)]['measurement'].mean())        

mean_relu = np.array(mean_relu)
mean_tanh = np.array(mean_tanh)
mean_sigmoid = np.array(mean_sigmoid)

In [4]:
mean_tanh_add = mean_tanh - mean_relu
mean_sigmoid_add = mean_sigmoid - mean_relu
print(mean_tanh_add)
print(mean_sigmoid_add)


[[263.635 193.797 126.927  88.005  43.875   3.49 ]
 [175.836 129.845 101.746  69.255  34.342   2.97 ]
 [126.728 102.022  74.954  50.685  25.185   2.01 ]
 [ 77.917  64.06   47.723  31.561  15.763   1.898]]
[[87.588 82.041 56.656 35.129 17.159  1.007]
 [41.847 37.118 38.874 28.037 13.579  1.878]
 [47.888 39.003 27.625 20.112  9.264  1.   ]
 [28.207 23.199 18.805 12.164  6.275  0.899]]


In [5]:
color_map = {6: 'rgb(255,0,0)', 5: 'rgb(0,255,0)', 4: 'rgb(0,0,255)', 3: 'rgb(255,255,0)'}
fig = go.Figure()
fig.add_trace(go.Scatter(x=num_neurons,y=mean_tanh_add[0,:],name='4',marker={'color': color_map[6]}))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_tanh_add[1,:],name='3',marker={'color': color_map[5]}))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_tanh_add[2,:],name='2',marker={'color': color_map[4]}))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_tanh_add[3,:],name='1',marker={'color': color_map[3]}))

fig.add_trace(go.Scatter(x=num_neurons,y=mean_sigmoid_add[0,:],marker={'color': color_map[6]},line={'dash':'dash'},showlegend=False))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_sigmoid_add[1,:],marker={'color': color_map[5]},line={'dash':'dash'},showlegend=False))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_sigmoid_add[2,:],marker={'color': color_map[4]},line={'dash':'dash'},showlegend=False))
fig.add_trace(go.Scatter(x=num_neurons,y=mean_sigmoid_add[3,:],marker={'color': color_map[3]},line={'dash':'dash'},showlegend=False))

fig.update_layout(xaxis_title="Number of Neurons in each layer", yaxis_title="Variation to relu (%)")
fig.show()